#cloud-config
# LazyVim Devbox Cloud-Init Configuration
# This file is used to automatically configure the CT on first boot

users:
  - name: dev
    groups: [sudo]
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_authorized_keys:
      - ${SSH_PUBLIC_KEY}

package_update: true
package_upgrade: false

packages:
  - curl
  - wget
  - git
  - sudo

runcmd:
  # Create workspace directory
  - mkdir -p /workspace
  - chown dev:dev /workspace
  
  # Download and run setup script
  - |
    curl -fsSL https://raw.githubusercontent.com/TejGandham/lazyvimmer/main/setup.sh -o /tmp/setup.sh
    chmod +x /tmp/setup.sh
    GITHUB_RAW_URL="https://raw.githubusercontent.com/TejGandham/lazyvimmer/main" \
    INSTALL_USER=dev \
    WORKSPACE_DIR=/workspace \
    /tmp/setup.sh --unattended
  
  # Set a marker that setup is complete
  - touch /var/lib/cloud/instance/boot-finished
  - echo "LazyVim Devbox setup completed at $(date)" >> /var/log/lazyvim-setup.log
  
  # Send completion notification (optional)
  - |
    if command -v wall >/dev/null 2>&1; then
      echo "LazyVim Devbox setup complete! You can now SSH as 'dev' user." | wall
    fi

final_message: |
  LazyVim Devbox setup complete!
  SSH access: ssh dev@$IPADDRESS
  Neovim will be ready on first login.

power_state:
  mode: reboot
  timeout: 30
  condition: True